-- ============================================================================
-- TASK CHECKBOXES TABLE MIGRATION
-- ============================================================================
-- This table stores subtasks/checkboxes for exams and exercises
-- Checkboxes can be generated by LLM or added manually by students
-- 
-- Run this script against your PostgreSQL database:
-- Host: dpg-d52n98u3jp1c73c7v2jg-a.virginia-postgres.render.com
-- Database: n8n_school_ozeh
-- ============================================================================

-- Create the task_checkboxes table
CREATE TABLE IF NOT EXISTS task_checkboxes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Task reference (polymorphic - references either exams or exercises)
    task_id UUID NOT NULL,
    task_type VARCHAR(20) NOT NULL CHECK (task_type IN ('exam', 'exercise')),
    
    -- Student who owns this checkbox list
    student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Checkbox content
    title TEXT NOT NULL,
    is_completed BOOLEAN DEFAULT false,
    position INTEGER DEFAULT 0,
    
    -- Tracking how it was created
    generated_by VARCHAR(20) DEFAULT 'manual' CHECK (generated_by IN ('llm', 'manual')),
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Primary lookup: Get all checkboxes for a specific task and student
CREATE INDEX IF NOT EXISTS idx_checkboxes_task_student 
    ON task_checkboxes(task_id, task_type, student_id);

-- Filter by completion status
CREATE INDEX IF NOT EXISTS idx_checkboxes_completed 
    ON task_checkboxes(student_id, is_completed);

-- Order by position within a task
CREATE INDEX IF NOT EXISTS idx_checkboxes_position 
    ON task_checkboxes(task_id, task_type, student_id, position);

-- ============================================================================
-- TRIGGER: Auto-update updated_at timestamp
-- ============================================================================

CREATE OR REPLACE FUNCTION update_checkbox_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_checkbox_timestamp ON task_checkboxes;

CREATE TRIGGER trigger_update_checkbox_timestamp
    BEFORE UPDATE ON task_checkboxes
    FOR EACH ROW
    EXECUTE FUNCTION update_checkbox_timestamp();

-- ============================================================================
-- SAMPLE DATA (OPTIONAL - for testing)
-- ============================================================================

-- Sample checkboxes for the first exercise (Programming Assignment: Binary Trees)
-- Student: Alice Martin (33333333-3333-3333-3333-333333333333)
INSERT INTO task_checkboxes (task_id, task_type, student_id, title, position, generated_by) VALUES
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Review binary tree concepts from lecture notes', 1, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Implement the BinaryNode class with left/right pointers', 2, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Implement insert() method for BST', 3, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Implement delete() method with all three cases', 4, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Implement inorder, preorder, and postorder traversals', 5, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Write unit tests for all operations', 6, 'llm'),
    ('55551111-1111-1111-1111-111111111111', 'exercise', '33333333-3333-3333-3333-333333333333', 
     'Document code with docstrings', 7, 'manual')
ON CONFLICT DO NOTHING;

-- Sample checkboxes for the midterm exam
INSERT INTO task_checkboxes (task_id, task_type, student_id, title, position, generated_by) VALUES
    ('eeee1111-1111-1111-1111-111111111111', 'exam', '33333333-3333-3333-3333-333333333333', 
     'Review sorting algorithms (bubble, merge, quick, heap)', 1, 'llm'),
    ('eeee1111-1111-1111-1111-111111111111', 'exam', '33333333-3333-3333-3333-333333333333', 
     'Practice Big-O complexity analysis', 2, 'llm'),
    ('eeee1111-1111-1111-1111-111111111111', 'exam', '33333333-3333-3333-3333-333333333333', 
     'Review data structures: arrays, linked lists, stacks, queues', 3, 'llm'),
    ('eeee1111-1111-1111-1111-111111111111', 'exam', '33333333-3333-3333-3333-333333333333', 
     'Study tree and graph algorithms', 4, 'llm'),
    ('eeee1111-1111-1111-1111-111111111111', 'exam', '33333333-3333-3333-3333-333333333333', 
     'Complete practice problems from chapters 4-8', 5, 'llm')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check table was created
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'task_checkboxes'
-- ORDER BY ordinal_position;

-- Check sample data
-- SELECT * FROM task_checkboxes ORDER BY task_id, position;
